### ISSUE TITLE
Ghost representation

### ISSUE THREAD

**Issue by subzey** [codegolf/pac-man#19]
Currenly ghost is represended by `x` character, that is 3 bytes in code, `"x"` _(and it would be 5 bytes if my PR #18 is accepted)_.

Could we replace it with `0` or any other scary ghostly looking digit?

**Comment by aemkei** [comment]
How about using a pac-man like "c" for the player and "0" for the ghost?

**Comment by bburky** [comment]
Sadly, GHOST (U+1F47B) 👻 would take even more bytes or I would suggest it.

**Comment by p01** [comment]
I thought `@`, `£`and `&` make decent ASCII characters.
