### ISSUE TITLE
You can't die

### ISSUE THREAD

**Issue by thiemowmde** [codegolf/pac-man#4]
Currently you can't die.
- `e` is the indicator for "game over" but is currently not used.
- You can see an unused `Q` in the code. I tried to figure out where it came from but wasn't able to based in the available history.

**Comment by aemkei** [comment]
The e&&Q was used to end the game. Q is not defined so it will break the interval and keep the last state. This hack was suggested by 0ndras to save some if…elses.

**Comment by thiemowmde** [comment]
So the game ends with an actual error printed on the console? o_O Well, seems I'm way to deep into clean code these days to enjoy such hacks.

**Comment by xem** [comment]
This hack was used on 140byt.es to stop a 140-byte sudoku solver. It's
acceptable IMO.
